### ISSUE TITLE
Train on new Data only

### ISSUE THREAD

**Issue by Avaneesh-S** [Dishant-P/S-Extension-patch-Official-research-module#1]
is there a way to load a pre trained model trained on COCO and then only pass new dataset to this and by using the S extension method train it to detect the new object class also ?

**Comment by Dishant-P** [comment]
Yes, certainly. Given it satisfies the similarity condition with any one/more COCO classes.

**Comment by Avaneesh-S** [comment]
can you please add an instructions file that tells how to load a pre trained model (eg: ssd_mobilenet_v2 trained on COCO 2017) and then only store the new object class dataset and then train the model to detect the old classes as well as new ones
